site_name: Ryu
site_description: Material 3 components for Qt 6 and QML
site_url: https://ryu.safalski.ryzn.pro/
repo_url: https://github.com/Happilli/ryu
repo_name: Happilli/ryu

theme:
  name: material
  palette:
    - scheme: ryu-dark
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: ryu-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Inter
    code: JetBrains Mono
  favicon: dragon.svg
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/dragon
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Extraa:
      - WavyProgress: extraa/wavy-progress.md
      - MaterialSlider: extraa/material-slider.md
  - Shapes:
      - MaterialShape: shapes/material-shape.md
extra:
  generator: false
